// Code generated by protoc-gen-go.
// source: blog.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	blog.proto
	im.proto

It has these top-level messages:
	HelloRequest
	HelloReply
	GetListRequest
	GetListReply
	ImHelloRequest
	ImHelloReply
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HelloRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *HelloRequest) Reset()                    { *m = HelloRequest{} }
func (m *HelloRequest) String() string            { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()               {}
func (*HelloRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloReply struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *HelloReply) Reset()                    { *m = HelloReply{} }
func (m *HelloReply) String() string            { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()               {}
func (*HelloReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetListRequest struct {
	Url string `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
}

func (m *GetListRequest) Reset()                    { *m = GetListRequest{} }
func (m *GetListRequest) String() string            { return proto.CompactTextString(m) }
func (*GetListRequest) ProtoMessage()               {}
func (*GetListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetListRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type GetListReply struct {
	Data []*GetListReply_Data `protobuf:"bytes,1,rep,name=data" json:"data,omitempty"`
	Next string               `protobuf:"bytes,2,opt,name=next" json:"next,omitempty"`
}

func (m *GetListReply) Reset()                    { *m = GetListReply{} }
func (m *GetListReply) String() string            { return proto.CompactTextString(m) }
func (*GetListReply) ProtoMessage()               {}
func (*GetListReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetListReply) GetData() []*GetListReply_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *GetListReply) GetNext() string {
	if m != nil {
		return m.Next
	}
	return ""
}

type GetListReply_Data struct {
	Img         string   `protobuf:"bytes,1,opt,name=img" json:"img,omitempty"`
	Title       string   `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Description string   `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	CreateAt    string   `protobuf:"bytes,4,opt,name=createAt" json:"createAt,omitempty"`
	Tags        []string `protobuf:"bytes,5,rep,name=tags" json:"tags,omitempty"`
	Category    string   `protobuf:"bytes,6,opt,name=category" json:"category,omitempty"`
	Link        string   `protobuf:"bytes,7,opt,name=link" json:"link,omitempty"`
}

func (m *GetListReply_Data) Reset()                    { *m = GetListReply_Data{} }
func (m *GetListReply_Data) String() string            { return proto.CompactTextString(m) }
func (*GetListReply_Data) ProtoMessage()               {}
func (*GetListReply_Data) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 0} }

func (m *GetListReply_Data) GetImg() string {
	if m != nil {
		return m.Img
	}
	return ""
}

func (m *GetListReply_Data) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *GetListReply_Data) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *GetListReply_Data) GetCreateAt() string {
	if m != nil {
		return m.CreateAt
	}
	return ""
}

func (m *GetListReply_Data) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *GetListReply_Data) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *GetListReply_Data) GetLink() string {
	if m != nil {
		return m.Link
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "pb.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "pb.HelloReply")
	proto.RegisterType((*GetListRequest)(nil), "pb.GetListRequest")
	proto.RegisterType((*GetListReply)(nil), "pb.GetListReply")
	proto.RegisterType((*GetListReply_Data)(nil), "pb.GetListReply.Data")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for BlogServer service

type BlogServerClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	GetList(ctx context.Context, in *GetListRequest, opts ...grpc.CallOption) (*GetListReply, error)
}

type blogServerClient struct {
	cc *grpc.ClientConn
}

func NewBlogServerClient(cc *grpc.ClientConn) BlogServerClient {
	return &blogServerClient{cc}
}

func (c *blogServerClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := grpc.Invoke(ctx, "/pb.BlogServer/SayHello", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogServerClient) GetList(ctx context.Context, in *GetListRequest, opts ...grpc.CallOption) (*GetListReply, error) {
	out := new(GetListReply)
	err := grpc.Invoke(ctx, "/pb.BlogServer/GetList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for BlogServer service

type BlogServerServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	GetList(context.Context, *GetListRequest) (*GetListReply, error)
}

func RegisterBlogServerServer(s *grpc.Server, srv BlogServerServer) {
	s.RegisterService(&_BlogServer_serviceDesc, srv)
}

func _BlogServer_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServerServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BlogServer/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServerServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlogServer_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogServerServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BlogServer/GetList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogServerServer).GetList(ctx, req.(*GetListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BlogServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.BlogServer",
	HandlerType: (*BlogServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _BlogServer_SayHello_Handler,
		},
		{
			MethodName: "GetList",
			Handler:    _BlogServer_GetList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "blog.proto",
}

func init() { proto.RegisterFile("blog.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 314 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x5c, 0x91, 0x4f, 0x6a, 0xf3, 0x30,
	0x10, 0xc5, 0xe3, 0xd8, 0xf9, 0xf3, 0x4d, 0x42, 0x08, 0xe2, 0x2b, 0x88, 0xac, 0x8c, 0x16, 0x25,
	0xdd, 0x18, 0x9a, 0x9e, 0xa0, 0xa5, 0xd0, 0x2e, 0xba, 0x4a, 0x4e, 0x20, 0x27, 0x83, 0x10, 0x95,
	0x23, 0x57, 0x9e, 0x94, 0x78, 0xd7, 0x23, 0xf5, 0x88, 0x45, 0x8a, 0x1c, 0xdc, 0xee, 0xde, 0xd3,
	0xfc, 0x2c, 0x3d, 0xbf, 0x01, 0x28, 0x8d, 0x55, 0x45, 0xed, 0x2c, 0x59, 0x36, 0xac, 0x4b, 0x21,
	0x60, 0xfe, 0x8a, 0xc6, 0xd8, 0x2d, 0x7e, 0x9c, 0xb0, 0x21, 0xc6, 0x20, 0x3b, 0xca, 0x0a, 0x79,
	0x92, 0x27, 0xeb, 0x7f, 0xdb, 0xa0, 0xc5, 0x2d, 0x40, 0x64, 0x6a, 0xd3, 0x32, 0x0e, 0x93, 0x0a,
	0x9b, 0x46, 0xaa, 0x0e, 0xea, 0xac, 0x10, 0xb0, 0x78, 0x41, 0x7a, 0xd3, 0x0d, 0x75, 0xb7, 0x2d,
	0x21, 0x3d, 0x39, 0x13, 0x39, 0x2f, 0xc5, 0xd7, 0x10, 0xe6, 0x57, 0xc8, 0x5f, 0x77, 0x07, 0xd9,
	0x41, 0x92, 0xe4, 0x49, 0x9e, 0xae, 0x67, 0x9b, 0x9b, 0xa2, 0x2e, 0x8b, 0xfe, 0xbc, 0x78, 0x96,
	0x24, 0xb7, 0x01, 0x09, 0xd9, 0xf0, 0x4c, 0x7c, 0x18, 0xb3, 0xe1, 0x99, 0x56, 0xdf, 0x09, 0x64,
	0x1e, 0xf1, 0x4f, 0xe9, 0x4a, 0x75, 0x4f, 0xe9, 0x4a, 0xb1, 0xff, 0x30, 0x22, 0x4d, 0x06, 0x23,
	0x7f, 0x31, 0x2c, 0x87, 0xd9, 0x01, 0x9b, 0xbd, 0xd3, 0x35, 0x69, 0x7b, 0xe4, 0x69, 0x98, 0xf5,
	0x8f, 0xd8, 0x0a, 0xa6, 0x7b, 0x87, 0x92, 0xf0, 0x91, 0x78, 0x16, 0xc6, 0x57, 0xef, 0x23, 0x90,
	0x54, 0x0d, 0x1f, 0xe5, 0xa9, 0x8f, 0xe0, 0x75, 0xe0, 0x25, 0xa1, 0xb2, 0xae, 0xe5, 0xe3, 0xc8,
	0x47, 0xef, 0x79, 0xa3, 0x8f, 0xef, 0x7c, 0x72, 0x89, 0xec, 0xf5, 0xc6, 0x02, 0x3c, 0x19, 0xab,
	0x76, 0xe8, 0x3e, 0xd1, 0xb1, 0x02, 0xa6, 0x3b, 0xd9, 0x86, 0x7e, 0xd9, 0xd2, 0xff, 0x7d, 0x7f,
	0x1d, 0xab, 0x45, 0xef, 0xa4, 0x36, 0xad, 0x18, 0xb0, 0x7b, 0x98, 0xc4, 0x7e, 0x18, 0xfb, 0x55,
	0xd6, 0xe5, 0x83, 0xe5, 0xdf, 0x02, 0xc5, 0xa0, 0x1c, 0x87, 0x75, 0x3f, 0xfc, 0x04, 0x00, 0x00,
	0xff, 0xff, 0xb5, 0x5e, 0xfa, 0x01, 0xfc, 0x01, 0x00, 0x00,
}
