[AppServer]
    Addr = "8080"
    RunMode="debug"
    ReadTimeout=10
    WriteTimeout=10
    BlogServerAddr = "127.0.0.1:8081"
[BlogServer]
    Addr = ":8081"
    IxugoDomain="localhost"
    WangboDomain="localhost"
    EsAddresses= ["http://127.0.0.1:9200"]
[ImServer]
    Addr = ":8082"
[Log]
    Path="logs"
